### PR TITLE
New Artwork, New Filename Structure, and a Few Language Updates

### PR DESCRIPTION
**Pull request by MichaelTunnell**
I didn't know what version to list it as so I just did 3.1.1 and please double check the TORked artwork because I was having issues with that one item though it did work in some cases. I'm not sure what the issue was when it didn't show to me correctly.

### CODE REVIEW

**Comment by keobrien08** [comment]
only issue i may have was that the logos that were used were provided by Angela, I think they were trying to standardize the brand

**Comment by RobLoach** [comment]
These look so awesome! :+1: ... Anything missing before a merge?

Perhaps just an update in the .xml for the new 3.1.1 version, I suppose.

**Comment by MichaelTunnell** [comment]
@keobrien08 
the updated logo I used was also from Angela. The black and white is for use on things that require one color only such as t-shirt printing. The Blue and Grey logo is also included in the logo pack. I did however add some extra touches to it to make it pop more.

@RobLoach 
Thanks. :)

I didn't add the 3.1.1 thing to the addon.xml file so if that is needed then yea my bad. I tried to modify everything necessary but it is possible I missed that file.

Should I update my branch and send a new pull request?

**Comment by RobLoach** [comment]
Checked TORked logo and it looked perfect here :+1: . Well done, @MichaelTunnell. I'll update the version in addon.xml, and put up a new fanart.jpg of the right size. Thanks so much!

**Pull request merged**
