### PR TITLE
Add BSD Now

### PR DESCRIPTION
**Pull request by RobLoach**
From Kerry O'Brien.

Things left to do:
- [x] Add BSD Now Image
- [x] Full peer review
- [x] Full code review

### CODE REVIEW

**Comment by ghost** [comment]
Ok, I created an acccount, I will try and do this correctly.

**Comment by ghost** [comment]
so I did git clone https://https://github.com/RobLoach/plugin.video.jupiterbroadcasting bsdnow, and I made my changes and reviewed, now I dont know how I push it back to you :/. You would think with so many tutorials out there this would be easy but its so overwhelming

**Comment by RobLoach** [comment]
Glad you got the code checkout. This is where it gets a little tricky, but once you get it, you'll be a github Pro :+1: . What you'll have to do is:
1. Create a fork of the project - There's a Fork button at the top right of it. You'll end up with `keobrien08/plugin.video.jupiterbroadcasting` . You can read more about that at https://help.github.com/articles/fork-a-repo
2. Check out your own fork. git clone <forkurl>
3. Switch to the bsdnow branch...  git checkout bsdnow
4. Commit your changes.... git add -A..... git commit -m "BSD Now changes"
5. Push the changes to your fork's bsdnow branch.... git push origin bsdnow
6. Submit a Pull Request to this bsdnow branch. You can read about those over at https://help.github.com/articles/using-pull-requests .

I know it's a lot of steps, but once you get it, you'll be an open source god. Usually it's just submit pull requests to a "master" branch, but this is a bit different since it's going to the bsdnow branch. Pull Request on a Pull Request. Pull Request-ception, if you will. If you have troubles, we could just do it in other means. Options! Thanks so much for this, so excited.

**Comment by ghost** [comment]
I think I got it all figured out. You should have a commit 14 from keobrien08.

**Comment by RobLoach** [comment]
Very nice, thanks a lot! Found a new logo for it, then will merge this one in. Well done, @keobrien08!

**Pull request merged**
