### PR TITLE
Add unit test support for shows

### PR DESCRIPTION
**Pull request by rickyphewitt**
fixes #62. Initial commit of unit test framework. This contains 4 tests for shows and factors out the jb shows/methods into their own module.

### CODE REVIEW

**Comment by RobLoach** [comment]
Any reason for both `jbshows` and `jb_shows`?

**Comment by rickyphewitt** [comment]
Only that I forgot to delete jbshows after a rename :) Let me update the commit

**Comment by rickyphewitt** [comment]
Updated branch to remove the extra file.

**Comment by rickyphewitt** [comment]
@RobLoach any thoughts on improvements or changes for this update? I'd like to start unit testing the rest of the code, but want to get the base framework in first.

**Comment by RobLoach** [comment]
Would Travis be able to run these?

**Pull request merged**
