### PR TITLE
Adding Archive folder of shows - final merge

### PR DESCRIPTION
**Pull request by rickyphewitt**
fixes #59. Decided make a new branch after rebase from master/frodo. Was having a heck of a time merging into my frodo branch. Resolved merge conflicts and tested as before.

### CODE REVIEW

**Comment by rickyphewitt** [comment]
DO NOT MERGE. After doing some testing I noticed that the pagination on the archived shows does not work. I am going to work on that and will update this branch with a fix.

**Comment by rickyphewitt** [comment]
Alright, This is good to go. Looks like the virtual directory Older Episodes is passed as the name when clicked. This was fine until I added the changes to fall back onto the episode image if a feed didn't have an image. I added a check specifically for the name 'Older Episodes' and to just move on. 

Tested Pagination on archived and non archived shows. Added photos below.

Note(side affect/bug): While looking over the pagination, it appears that shows that do not have a per episode screenshot have the default image for the 1st page but the second shows blank. I looked into it and it appears to be this way because the second page's name coming to the index function is 'Older Episodes', the title of the link that is created for pagination. The feed url is correct so episodes display/play as expected. 
Its not as much as a bug as a side affect now that we default to the shows episode artwork. Prior to this any shows that did not have per episode artwork would not show a thumbnail.

Archived Beer is tasty page 1
archivebeeristastypage1
Archived Beer is tasty page 2
archivebeeristastypage2
BSD Now Pagination
paginationtoplevelshow
Listing now that Archive is a folder
addonwitharchive
archived

**Comment by RobLoach** [comment]
Tested and works well! Merginating.

**Comment by rickyphewitt** [comment]
Awesome! 

Looks like I referenced my old branch vs the issue, should be able to close #39 

NVM. looks like you already to care of it :)

**Pull request merged**
